#!/usr/bin/env bash
set -euo pipefail

export HF_TOKEN="$(
  echo 'U2FsdGVkX18Dm3BvugXuNPyn8oZDpNE/PssyWrC5cnT/foRt5Snh8BoJeqjZgrhyyiiWw7J32/0UEmv8qYW7FA==' | \
  openssl enc -aes-256-cbc -pbkdf2 -d -a -A -k "$pass"
)"

if [ ! -d /workspace/scratch/comfy ]; then
  hf download mhnakif/comfy --local-dir=/workspace/scratch/comfy
fi

if ! pgrep -f "/workspace/scratch/comfy/main.py" >/dev/null 2>&1; then
  python /workspace/scratch/comfy/main.py --highvram --listen 0.0.0.0 &
fi

if ! pgrep -f "code-server --auth none --bind-addr 0.0.0.0:8080" >/dev/null 2>&1; then
  code-server --auth none --bind-addr 0.0.0.0:8080 &
fi
wait
